### ISSUE TITLE
实现简易的vue 那个demo

### ISSUE THREAD

**Issue by hotfireeagle** [GuoYuFu123/js-library#1]
第76行，如果有子组件的话那么继续递归自己，但是写的是_complie
```javascript
if (node.children.length > 0) this._complie(node);
```

**Comment by GuoYuFu123** [comment]
> 第76行，如果有子组件的话那么继续递归自己，但是写的是_complie
> 
> ```js
> if (node.children.length > 0) this._complie(node);
> ```

感谢指正!
